### PR TITLE
Fix bug #5604 - Unrecognised signal for touchable no longer on the sc…

### PR DESCRIPTION
**Pull request by jimmyhmiller**
Cherry picked change to hopefully resolve https://github.com/BillHeroInc/ui/issues/925

### CODE REVIEW

**Comment by trabianmatt** [comment]
Actually -- can you apply this to trabian-v0.22 instead? That's the branch I'm using.

**Comment by jimmyhmiller** [comment]
I can. That doesn't appear to be the branch the git submodule is setup on. But I can definitely do that.

**Comment by trabianmatt** [comment]
I just pushed my latest. Maybe that's why you couldn't get it to run on the submodule.

**Comment by jimmyhmiller** [comment]
I'm still seeing 0.14 https://github.com/BillHeroInc/ui/blob/v2.0/.gitmodules#L4

**Comment by trabianmatt** [comment]
Odd - didn't know you could specify the branch like that in .gitmodules. Here's what I'm referencing:

https://github.com/BillHeroInc/ui/commit/6be98d2970a6f0fdbc907f2b8a7852f3bf267a7a

**Pull request merged**
